CREATE TABLE "prof_data" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "d2_number" varchar NOT NULL,
  "d2_profstroi" varchar NOT NULL,
  "d2_object" varchar NOT NULL,
  "d2_manager" varchar NOT NULL,
  "d2_kontragent" varchar NOT NULL,
  "d2_id" varchar NOT NULL,
  "d2_diler" varchar NOT NULL,
  "d2_city" varchar NOT NULL,
  "d2_napr" varchar NOT NULL,
  "d2_sum_proj_to_sk" varchar NOT NULL,
  "d2_sum_skidka" varchar NOT NULL,
  "d2_sum_proj_with_skidka" varchar NOT NULL,
  "d2_sum_constr_with_skidka" varchar NOT NULL,
  "d2_sum_rab_with_skidka" varchar NOT NULL,
  "d2_status" varchar NOT NULL,
  "note_order" varchar NOT NULL
);

CREATE TABLE "dem_klaes_materials" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "order_id" bigint NOT NULL,
  "size" varchar,
  "name" varchar,
  "count" varchar,
  "allowances" varchar,
  "color" varchar,
  "type" varchar,
  "price" varchar,
  "location" varchar,
  "width" varchar,
  "height" varchar,
  "gform" varchar,
  "nsq" varchar,
  "nRama" varchar,
  "Aug01" varchar,
  "Aug02" varchar,
  "cLke" varchar
);

ALTER TABLE "dem_klaes_materials" ADD FOREIGN KEY ("order_id") REFERENCES "prof_data" ("id");
